---
- include_vars: defaults.yml

- template: src=db_structure.sql.j2 dest={{PATH_WWW}}/{{PATH_ADMIN_DIR}}/misc/database_structure_mysql/db_structure.sql
- shell: mysql  < /{{PATH_WWW}}/{{PATH_ADMIN_DIR}}/misc/database_structure_mysql/db_structure.sql
  ignore_errors: yes
